import json

with open("corridas.json", "r") as f:
    db = json.load(f)

    ont = """
#################################################################
#    Individuals
#################################################################
"""
    estados = set()
    numeros = set()

    for c in db:
        estados.add(c['estado'])

        if (c['número'] in estados): continue
        numeros.add(c['número'])

        ont += f"""
###  http://rpcw.di.uminho.pt/corridas#{c['nome']}
:{c['nome']} rdf:type owl:NamedIndividual ;
       :viveEm :{c['estado'].replace(' ', '_')} ;
       :hobby "{c['hobby']}" ;
       :número {c['número']} ;
       :nome "{c['nome']}" ;
       :idade {c['idade']} ;
       :tshirt "{c['tshirt']}" .
        """.strip()
        ont += "\n\n\n"

    for e in estados:
        e_ = e.replace(" ", "_")
        ont += f"""
###  http://rpcw.di.uminho.pt/corridas#{e_}
:{e_} rdf:type owl:NamedIndividual,
                        :Estado .
        """.strip()
        ont += "\n\n\n"

    ont += "###  Generated by RPCW2026 script 2026-02-03\n"

    print(ont)